language: ruby
cache: bundler
rvm:
  - 2.1.2
before_script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script: bundle exec rspec
services:
env:
notifications:
  email: false
